# Generated by Django 3.2.25 on 2025-09-18 21:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=300, verbose_name='Название организации')),
                ('contact_person', models.CharField(max_length=200, verbose_name='Контактное лицо')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('object_address', models.TextField(verbose_name='Адрес объекта')),
                ('object_description', models.TextField(verbose_name='Описание объекта')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('processed', models.BooleanField(default=False, verbose_name='Обработана')),
            ],
            options={
                'verbose_name': 'Запрос на аудит',
                'verbose_name_plural': 'Запросы на аудит',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(default='г. Москва М. Шоссе Энтузиастов 31 строение 38', max_length=500, verbose_name='Адрес')),
                ('phone_main', models.CharField(default='8-800-XXX-XX-XX', max_length=20, verbose_name='Основной телефон')),
                ('phone_emergency', models.CharField(default='8-800-XXX-XX-XX', max_length=20, verbose_name='Телефон аварийной службы')),
                ('phone_government', models.CharField(default='8-800-XXX-XX-XX', max_length=20, verbose_name='Телефон для госзаказчиков')),
                ('phone_technical', models.CharField(default='8-800-XXX-XX-XX', max_length=20, verbose_name='Отдел технического надзора')),
                ('phone_orders', models.CharField(default='8-800-XXX-XX-XX', max_length=20, verbose_name='Телефон для заказа услуг')),
            ],
            options={
                'verbose_name': 'Контактная информация',
                'verbose_name_plural': 'Контактная информация',
            },
        ),
        migrations.CreateModel(
            name='DownloadableDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название документа')),
                ('document_type', models.CharField(choices=[('audit_form', 'Форма заявки для аудита'), ('heating_form', 'Форма заявки для подготовки к отопительному сезону')], max_length=20, unique=True, verbose_name='Тип документа')),
                ('file', models.FileField(upload_to='documents/', verbose_name='Файл')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Документ для скачивания',
                'verbose_name_plural': 'Документы для скачивания',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('photo_type', models.CharField(choices=[('main_str1_1', 'Главная страница - Фото 1 (str1/photo1)'), ('main_str1_2', 'Главная страница - Фото 2 (str1/photo2)'), ('main_str1_3', 'Главная страница - Фото 3 (str1/photo3)'), ('main_str1_4', 'Главная страница - Фото 4 (str1/photo4)'), ('complex_str2_1', 'Комплексное обслуживание - Фото 1 (str2/photo5)'), ('complex_str2_2', 'Комплексное обслуживание - Фото 2 (str2/photo6)'), ('complex_str2_3', 'Комплексное обслуживание - Фото 3 (str2/photo7)'), ('complex_str2_4', 'Комплексное обслуживание - Фото 4 (str2/photo8)'), ('heating_str3_1', 'ИТП отопления - Фото (str3/photo9)'), ('emergency_str5_1', 'Аварийная служба - Фото 1 (str5/photo10)'), ('emergency_str5_2', 'Аварийная служба - Фото 2 (str5/photo11)'), ('emergency_str5_3', 'Аварийная служба - Фото 3 (str5/photo12)'), ('emergency_str5_4', 'Аварийная служба - Фото 4 (str5/photo13)')], max_length=20, unique=True, verbose_name='Тип фотографии')),
                ('image', models.ImageField(upload_to='photos/', verbose_name='Изображение')),
                ('alt_text', models.CharField(blank=True, max_length=200, verbose_name='Альтернативный текст')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Фотография',
                'verbose_name_plural': 'Фотографии',
            },
        ),
        migrations.CreateModel(
            name='ServiceApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('service_type', models.CharField(choices=[('complex_service', 'Комплексное обслуживание инженерных систем'), ('heating_service', 'Комплексное обслуживание систем (ИТП) отопления'), ('verification', 'Поверка приборов учёта'), ('emergency', 'Аварийная служба'), ('installation', 'Монтаж инженерных коммуникаций'), ('audit', 'Аудит инженерных систем'), ('heating_preparation', 'Подготовка к отопительному сезону'), ('ventilation', 'Вентиляция')], max_length=20, verbose_name='Тип услуги')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('processed', models.BooleanField(default=False, verbose_name='Обработана')),
            ],
            options={
                'verbose_name': 'Заявка на услугу',
                'verbose_name_plural': 'Заявки на услуги',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TenderInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон для связи')),
                ('company_name', models.CharField(blank=True, max_length=200, verbose_name='Название компании')),
                ('technical_task', models.FileField(blank=True, null=True, upload_to='tender_tasks/', verbose_name='Техническое задание')),
                ('agreed_to_processing', models.BooleanField(default=False, verbose_name='Согласие на обработку данных')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('processed', models.BooleanField(default=False, verbose_name='Обработана')),
            ],
            options={
                'verbose_name': 'Приглашение в тендер',
                'verbose_name_plural': 'Приглашения в тендер',
                'ordering': ['-created_at'],
            },
        ),
    ]
