# Generated by Django 3.2.25 on 2025-09-23 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20250921_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo_type',
            field=models.CharField(choices=[('main_str1_1', 'Главная страница - Фото 1 (str1/photo1)'), ('main_str1_2', 'Главная страница - Фото 2 (str1/photo2)'), ('main_str1_3', 'Главная страница - Фото 3 (str1/photo3)'), ('main_str1_4', 'Главная страница - Фото 4 (str1/photo4)'), ('main_gallery_1', 'Галерея в конце сайта - Фото 1 (str1/photo14)'), ('main_gallery_2', 'Галерея в конце сайта - Фото 2 (str1/photo15)'), ('main_gallery_3', 'Галерея в конце сайта - Фото 3 (str1/photo16)'), ('main_gallery_4', 'Галерея в конце сайта - Фото 4 (str1/photo17)'), ('heating_str3_1', 'ИТП отопления - Фото (str3/photo9)'), ('emergency_str5_1', 'Аварийная служба - Фото 1 (str5/photo10)'), ('emergency_str5_2', 'Аварийная служба - Фото 2 (str5/photo11)'), ('emergency_str5_3', 'Аварийная служба - Фото 3 (str5/photo12)'), ('emergency_str5_4', 'Аварийная служба - Фото 4 (str5/photo13)'), ('emergency_gallery_1', 'Аварийная служба галерея - Фото 1 (str5/photo10)'), ('emergency_gallery_2', 'Аварийная служба галерея - Фото 2 (str5/photo11)'), ('emergency_gallery_3', 'Аварийная служба галерея - Фото 3 (str5/photo12)'), ('emergency_gallery_4', 'Аварийная служба галерея - Фото 4 (str5/photo13)')], max_length=20, unique=True, verbose_name='Тип фотографии'),
        ),
    ]
