# Generated by Django 3.2.25 on 2025-09-24 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_alter_photo_photo_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo_type',
            field=models.CharField(choices=[('main_str1_1', 'Главная страница - Фото 1 (str1/photo1)'), ('main_str1_2', 'Главная страница - Фото 2 (str1/photo2)'), ('main_str1_3', 'Главная страница - Фото 3 (str1/photo3)'), ('main_str1_4', 'Главная страница - Фото 4 (str1/photo4)'), ('main_gallery_1', 'Галерея в конце сайта - Фото 1 (str1/photo14)'), ('main_gallery_2', 'Галерея в конце сайта - Фото 2 (str1/photo15)'), ('main_gallery_3', 'Галерея в конце сайта - Фото 3 (str1/photo16)'), ('main_gallery_4', 'Галерея в конце сайта - Фото 4 (str1/photo17)'), ('heating_str3_1', 'ИТП отопления - Фото (str3/photo9)'), ('heating_team_1', 'ИТП отопления - Команда 1 (str3/photo9)'), ('heating_team_2', 'ИТП отопления - Команда 2 (str3/photoFF)'), ('heating_gallery_1', 'ИТП отопления - Галерея 1 (str3/photou)'), ('heating_gallery_2', 'ИТП отопления - Галерея 2 (str3/photop)'), ('heating_gallery_3', 'ИТП отопления - Галерея 3 (str3/photoy)'), ('heating_gallery_4', 'ИТП отопления - Галерея 4 (str3/photog)'), ('verification_gallery_1', 'Поверка приборов - Галерея 1 (str4/photojk)'), ('verification_gallery_2', 'Поверка приборов - Галерея 2 (str4/photopkk)'), ('verification_gallery_3', 'Поверка приборов - Галерея 3 (str4/photoub)'), ('verification_gallery_4', 'Поверка приборов - Галерея 4 (str4/photogl)'), ('emergency_str5_1', 'Аварийная служба - Фото 1 (str5/photo10)'), ('emergency_str5_2', 'Аварийная служба - Фото 2 (str5/photo11)'), ('emergency_str5_3', 'Аварийная служба - Фото 3 (str5/photo12)'), ('emergency_str5_4', 'Аварийная служба - Фото 4 (str5/photo13)'), ('emergency_gallery_1', 'Аварийная служба галерея - Фото 1 (str5/photo10)'), ('emergency_gallery_2', 'Аварийная служба галерея - Фото 2 (str5/photo11)'), ('emergency_gallery_3', 'Аварийная служба галерея - Фото 3 (str5/photo12)'), ('emergency_gallery_4', 'Аварийная служба галерея - Фото 4 (str5/photo13)'), ('complex_team_1', 'Комплексное обслуживание - Команда 1 (str2/photo5)'), ('complex_team_2', 'Комплексное обслуживание - Команда 2 (str2/photo6)'), ('complex_electro_1', 'Комплексное обслуживание - Электрохозяйство 1 (str2/photo7)'), ('complex_electro_2', 'Комплексное обслуживание - Электрохозяйство 2 (str2/photo8)'), ('preparation_team_1', 'Подготовка к отопительному сезону - Команда 1 (str8/photoug)'), ('preparation_team_2', 'Подготовка к отопительному сезону - Команда 2 (str8/photoyk)'), ('ventilation_team_1', 'Вентиляция - Команда 1 (str9/vent1)'), ('ventilation_team_2', 'Вентиляция - Команда 2 (str9/vent2)')], max_length=30, unique=True, verbose_name='Тип фотографии'),
        ),
    ]
