# Generated by Django 3.2.25 on 2025-09-27 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_update_photo_titles'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='tender_invitation',
            field=models.TextField(blank=True, default='Приглашаем к участию в тендерах', max_length=1000, verbose_name='Текст приглашения в тендер'),
        ),
        migrations.AddField(
            model_name='serviceapplication',
            name='message',
            field=models.TextField(blank=True, null=True, verbose_name='Сообщение'),
        ),
        migrations.AddField(
            model_name='serviceapplication',
            name='organization',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Организация'),
        ),
        migrations.AddField(
            model_name='serviceapplication',
            name='preferred_time',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Удобное время для звонка'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='phone_main',
            field=models.CharField(default='8-800-XXX-XX-XX', max_length=20, verbose_name='Общий номер телефона (единый для всех страниц)'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo_type',
            field=models.CharField(choices=[('main_team_1', 'Главная страница - У нас работают люди, проверенные временем! - Фото 1'), ('main_team_2', 'Главная страница - У нас работают люди, проверенные временем! - Фото 2'), ('main_team_3', 'Главная страница - У нас работают люди, проверенные временем! - Фото 3'), ('main_team_4', 'Главная страница - У нас работают люди, проверенные временем! - Фото 4'), ('main_gallery_1', 'Главная страница - Живые фотографии с объектов - Фото 1'), ('main_gallery_2', 'Главная страница - Живые фотографии с объектов - Фото 2'), ('main_gallery_3', 'Главная страница - Живые фотографии с объектов - Фото 3'), ('main_gallery_4', 'Главная страница - Живые фотографии с объектов - Фото 4'), ('complex_team_1', 'Комплексное обслуживание - У нас работают люди, проверенные временем! - Фото 1'), ('complex_team_2', 'Комплексное обслуживание - У нас работают люди, проверенные временем! - Фото 2'), ('complex_team_3', 'Комплексное обслуживание - У нас работают люди, проверенные временем! - Фото 3'), ('complex_team_4', 'Комплексное обслуживание - У нас работают люди, проверенные временем! - Фото 4'), ('complex_gallery_1', 'Комплексное обслуживание - Живые фотографии с объектов - Фото 1'), ('complex_gallery_2', 'Комплексное обслуживание - Живые фотографии с объектов - Фото 2'), ('complex_gallery_3', 'Комплексное обслуживание - Живые фотографии с объектов - Фото 3'), ('complex_gallery_4', 'Комплексное обслуживание - Живые фотографии с объектов - Фото 4'), ('heating_professional_1', 'ИТП и ЦТП - Профессиональное обслуживание тепловых пунктов - Фото 1'), ('heating_professional_2', 'ИТП и ЦТП - Профессиональное обслуживание тепловых пунктов - Фото 2'), ('heating_professional_3', 'ИТП и ЦТП - Профессиональное обслуживание тепловых пунктов - Фото 3'), ('heating_professional_4', 'ИТП и ЦТП - Профессиональное обслуживание тепловых пунктов - Фото 4'), ('heating_gallery_1', 'ИТП и ЦТП - Фотографии с объектов - Фото 1'), ('heating_gallery_2', 'ИТП и ЦТП - Фотографии с объектов - Фото 2'), ('heating_gallery_3', 'ИТП и ЦТП - Фотографии с объектов - Фото 3'), ('heating_gallery_4', 'ИТП и ЦТП - Фотографии с объектов - Фото 4'), ('verification_gallery_1', 'Поверка приборов - Живые фотографии с объектов - Фото 1'), ('verification_gallery_2', 'Поверка приборов - Живые фотографии с объектов - Фото 2'), ('verification_gallery_3', 'Поверка приборов - Живые фотографии с объектов - Фото 3'), ('verification_gallery_4', 'Поверка приборов - Живые фотографии с объектов - Фото 4'), ('emergency_team_1', 'Аварийная служба - Команда специалистов аварийной службы - Фото 1'), ('emergency_team_2', 'Аварийная служба - Команда специалистов аварийной службы - Фото 2'), ('emergency_team_3', 'Аварийная служба - Команда специалистов аварийной службы - Фото 3'), ('emergency_team_4', 'Аварийная служба - Команда специалистов аварийной службы - Фото 4'), ('audit_gallery_1', 'Аудит систем - Живые фотографии с объектов - Фото 1'), ('audit_gallery_2', 'Аудит систем - Живые фотографии с объектов - Фото 2'), ('audit_gallery_3', 'Аудит систем - Живые фотографии с объектов - Фото 3'), ('audit_gallery_4', 'Аудит систем - Живые фотографии с объектов - Фото 4'), ('preparation_gallery_1', 'Подготовка к отопительному сезону - Фотографии с объектов - Фото 1'), ('preparation_gallery_2', 'Подготовка к отопительному сезону - Фотографии с объектов - Фото 2'), ('preparation_gallery_3', 'Подготовка к отопительному сезону - Фотографии с объектов - Фото 3'), ('preparation_gallery_4', 'Подготовка к отопительному сезону - Фотографии с объектов - Фото 4'), ('ventilation_team_1', 'Техническое обслуживание климатических систем - Команда специалистов по вентиляции - Фото 1'), ('ventilation_team_2', 'Техническое обслуживание климатических систем - Команда специалистов по вентиляции - Фото 2'), ('ventilation_team_3', 'Техническое обслуживание климатических систем - Команда специалистов по вентиляции - Фото 3'), ('ventilation_team_4', 'Техническое обслуживание климатических систем - Команда специалистов по вентиляции - Фото 4')], max_length=30, unique=True, verbose_name='Тип фотографии'),
        ),
        migrations.AlterField(
            model_name='serviceapplication',
            name='request_type',
            field=models.CharField(choices=[('application', 'Оставить заявку'), ('callback', 'Заказать звонок специалиста'), ('emergency_call', 'Вызвать аварийную службу'), ('quote_request', 'Запросить КП/коммерческое предложение'), ('phone_call', 'Позвонить сейчас')], default='application', max_length=20, verbose_name='Тип заявки'),
        ),
        migrations.AlterField(
            model_name='serviceapplication',
            name='service_type',
            field=models.CharField(choices=[('main_page', 'Главная страница'), ('complex_service', 'Комплексное обслуживание инженерных систем'), ('heating_service', 'Комплексное обслуживание ИТП и ЦТП «под ключ»'), ('verification', 'Поверка, ремонт и восстановление приборов учета'), ('emergency', 'Аварийная служба'), ('installation', 'Монтаж инженерных коммуникаций'), ('audit', 'Аудит инженерных систем для госзаказчиков'), ('heating_preparation', 'Подготовка к отопительному сезону'), ('ventilation', 'Профессиональное техническое обслуживание климатических систем')], max_length=30, verbose_name='Страница-источник'),
        ),
    ]
