# Generated by Django 3.2.25 on 2025-09-27 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_auto_20250927_1251'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('gallery_type', models.CharField(choices=[('main_objects', 'Главная страница - Живые фотографии с объектов'), ('complex_objects', 'Комплексное обслуживание - Живые фотографии с объектов'), ('heating_objects', 'ИТП и ЦТП - Фотографии с объектов'), ('verification_objects', 'Поверка приборов - Живые фотографии с объектов'), ('audit_objects', 'Аудит систем - Живые фотографии с объектов'), ('preparation_objects', 'Подготовка к отопительному сезону - Фотографии с объектов')], max_length=30, verbose_name='Тип галереи')),
                ('image', models.ImageField(upload_to='gallery/', verbose_name='Изображение')),
                ('alt_text', models.CharField(blank=True, max_length=200, verbose_name='Альтернативный текст')),
                ('order', models.PositiveIntegerField(default=0, help_text='Чем меньше число, тем раньше отображается', verbose_name='Порядок отображения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активная')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Фото в галерее',
                'verbose_name_plural': 'Галерея фотографий',
                'ordering': ['gallery_type', 'order', 'created_at'],
            },
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo_type',
            field=models.CharField(choices=[('main_team_1', 'Главная страница - У нас работают люди, проверенные временем! - Фото 1'), ('main_team_2', 'Главная страница - У нас работают люди, проверенные временем! - Фото 2'), ('main_team_3', 'Главная страница - У нас работают люди, проверенные временем! - Фото 3'), ('main_team_4', 'Главная страница - У нас работают люди, проверенные временем! - Фото 4'), ('complex_team_1', 'Комплексное обслуживание - У нас работают люди, проверенные временем! - Фото 1'), ('complex_team_2', 'Комплексное обслуживание - У нас работают люди, проверенные временем! - Фото 2'), ('complex_team_3', 'Комплексное обслуживание - У нас работают люди, проверенные временем! - Фото 3'), ('complex_team_4', 'Комплексное обслуживание - У нас работают люди, проверенные временем! - Фото 4'), ('heating_professional_1', 'ИТП и ЦТП - Профессиональное обслуживание тепловых пунктов - Фото 1'), ('heating_professional_2', 'ИТП и ЦТП - Профессиональное обслуживание тепловых пунктов - Фото 2'), ('heating_professional_3', 'ИТП и ЦТП - Профессиональное обслуживание тепловых пунктов - Фото 3'), ('heating_professional_4', 'ИТП и ЦТП - Профессиональное обслуживание тепловых пунктов - Фото 4'), ('emergency_team_1', 'Аварийная служба - Команда специалистов аварийной службы - Фото 1'), ('emergency_team_2', 'Аварийная служба - Команда специалистов аварийной службы - Фото 2'), ('emergency_team_3', 'Аварийная служба - Команда специалистов аварийной службы - Фото 3'), ('emergency_team_4', 'Аварийная служба - Команда специалистов аварийной службы - Фото 4'), ('ventilation_team_1', 'Техническое обслуживание климатических систем - Команда специалистов по вентиляции - Фото 1'), ('ventilation_team_2', 'Техническое обслуживание климатических систем - Команда специалистов по вентиляции - Фото 2'), ('ventilation_team_3', 'Техническое обслуживание климатических систем - Команда специалистов по вентиляции - Фото 3'), ('ventilation_team_4', 'Техническое обслуживание климатических систем - Команда специалистов по вентиляции - Фото 4')], max_length=30, unique=True, verbose_name='Тип фотографии'),
        ),
    ]
