# Generated by Django 3.2.25 on 2025-09-29 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_auto_20250927_1303'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuditRequest',
        ),
        migrations.CreateModel(
            name='AuditGalleryGroup',
            fields=[
            ],
            options={
                'verbose_name': 'Галерея Аудит инженерных систем для госзаказчиков',
                'verbose_name_plural': 'Галерея Аудит инженерных систем для госзаказчиков',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('website.galleryphoto',),
        ),
        migrations.CreateModel(
            name='ComplexGalleryGroup',
            fields=[
            ],
            options={
                'verbose_name': 'Галерея Комплексное обслуживание инженерных систем',
                'verbose_name_plural': 'Галерея Комплексное обслуживание инженерных систем',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('website.galleryphoto',),
        ),
        migrations.CreateModel(
            name='EmergencyPhotoGroup',
            fields=[
            ],
            options={
                'verbose_name': 'Фото Аварийная служба',
                'verbose_name_plural': 'Фото Аварийная служба',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('website.photo',),
        ),
        migrations.CreateModel(
            name='GalleryGroup',
            fields=[
            ],
            options={
                'verbose_name': 'Фотогалерея',
                'verbose_name_plural': 'Фотогалерея',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('website.galleryphoto',),
        ),
        migrations.CreateModel(
            name='HeatingGalleryGroup',
            fields=[
            ],
            options={
                'verbose_name': 'Галерея Комплексное обслуживание ИТП и ЦТП «под ключ»',
                'verbose_name_plural': 'Галерея Комплексное обслуживание ИТП и ЦТП «под ключ»',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('website.galleryphoto',),
        ),
        migrations.CreateModel(
            name='HeatingPhotoGroup',
            fields=[
            ],
            options={
                'verbose_name': 'Фото Комплексное обслуживание ИТП и ЦТП «под ключ»',
                'verbose_name_plural': 'Фото Комплексное обслуживание ИТП и ЦТП «под ключ»',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('website.photo',),
        ),
        migrations.CreateModel(
            name='PhotoGroup',
            fields=[
            ],
            options={
                'verbose_name': 'Фото',
                'verbose_name_plural': 'Фото',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('website.photo',),
        ),
        migrations.CreateModel(
            name='PreparationGalleryGroup',
            fields=[
            ],
            options={
                'verbose_name': 'Галерея Подготовка к отопительному сезону',
                'verbose_name_plural': 'Галерея Подготовка к отопительному сезону',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('website.galleryphoto',),
        ),
        migrations.CreateModel(
            name='VentilationPhotoGroup',
            fields=[
            ],
            options={
                'verbose_name': 'Фото Профессиональное техническое обслуживание',
                'verbose_name_plural': 'Фото Профессиональное техническое обслуживание',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('website.photo',),
        ),
        migrations.CreateModel(
            name='VerificationGalleryGroup',
            fields=[
            ],
            options={
                'verbose_name': 'Галерея Поверка, ремонт и восстановление приборов учета',
                'verbose_name_plural': 'Галерея Поверка, ремонт и восстановление приборов учета',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('website.galleryphoto',),
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo_type',
            field=models.CharField(choices=[('main_team_1', 'Главная страница - У нас работают люди, проверенные временем! - Фото 1'), ('main_team_2', 'Главная страница - У нас работают люди, проверенные временем! - Фото 2'), ('main_team_3', 'Главная страница - У нас работают люди, проверенные временем! - Фото 3'), ('main_team_4', 'Главная страница - У нас работают люди, проверенные временем! - Фото 4'), ('emergency_photo_1', 'Аварийная служба - Фото 1'), ('emergency_photo_2', 'Аварийная служба - Фото 2'), ('complex_team_1', 'Комплексное обслуживание - У нас работают люди, проверенные временем! - Фото 1'), ('complex_team_2', 'Комплексное обслуживание - У нас работают люди, проверенные временем! - Фото 2'), ('complex_team_3', 'Комплексное обслуживание - У нас работают люди, проверенные временем! - Фото 3'), ('complex_team_4', 'Комплексное обслуживание - У нас работают люди, проверенные временем! - Фото 4'), ('heating_professional_1', 'ИТП и ЦТП - Профессиональное обслуживание тепловых пунктов - Фото 1'), ('heating_professional_2', 'ИТП и ЦТП - Профессиональное обслуживание тепловых пунктов - Фото 2'), ('heating_professional_3', 'ИТП и ЦТП - Профессиональное обслуживание тепловых пунктов - Фото 3'), ('heating_professional_4', 'ИТП и ЦТП - Профессиональное обслуживание тепловых пунктов - Фото 4'), ('emergency_team_1', 'Аварийная служба - Команда специалистов аварийной службы - Фото 1'), ('emergency_team_2', 'Аварийная служба - Команда специалистов аварийной службы - Фото 2'), ('emergency_team_3', 'Аварийная служба - Команда специалистов аварийной службы - Фото 3'), ('emergency_team_4', 'Аварийная служба - Команда специалистов аварийной службы - Фото 4'), ('ventilation_team_1', 'Техническое обслуживание климатических систем - Команда специалистов по вентиляции - Фото 1'), ('ventilation_team_2', 'Техническое обслуживание климатических систем - Команда специалистов по вентиляции - Фото 2'), ('ventilation_team_3', 'Техническое обслуживание климатических систем - Команда специалистов по вентиляции - Фото 3'), ('ventilation_team_4', 'Техническое обслуживание климатических систем - Команда специалистов по вентиляции - Фото 4')], max_length=30, unique=True, verbose_name='Тип фотографии'),
        ),
        migrations.AlterField(
            model_name='serviceapplication',
            name='service_type',
            field=models.CharField(choices=[('main_page', 'Главная страница'), ('complex_service', 'Комплексное обслуживание инженерных систем'), ('heating_service', 'Комплексное обслуживание ИТП и ЦТП «под ключ»'), ('verification_service', 'Поверка, ремонт и восстановление приборов учета'), ('emergency_service', 'Аварийная служба'), ('installation_service', 'Монтаж инженерных коммуникаций'), ('audit_service', 'Аудит инженерных систем для госзаказчиков'), ('heating_preparation_service', 'Подготовка к отопительному сезону'), ('ventilation_service', 'Профессиональное техническое обслуживание климатических систем')], max_length=30, verbose_name='Страница-источник'),
        ),
    ]
